Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # CONTROL NODE
  config.vm.define "control" do |control|
    control.vm.hostname = "control"
    control.vm.network "private_network", ip: "192.168.56.10"

    control.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end

    control.vm.provision "shell", path: "bootstrap.sh"
  end

  # WORKER 1
  config.vm.define "worker1" do |worker|
    worker.vm.hostname = "worker1"
    worker.vm.network "private_network", ip: "192.168.56.11"

    worker.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end

    worker.vm.provision "shell", path: "bootstrap.sh"
  end

  # WORKER 2
  config.vm.define "worker2" do |worker|
    worker.vm.hostname = "worker2"
    worker.vm.network "private_network", ip: "192.168.56.12"

    worker.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end

    worker.vm.provision "shell", path: "bootstrap.sh"
  end
end
